### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign in
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After signing up, a user is able to sign into their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 13 (1)](https://user-images.githubusercontent.com/68994507/184802990-80d00535-71bf-4dfe-bb9e-fb7d68ae92fa.png)

Desktop
![Group 16](https://user-images.githubusercontent.com/68994507/184802998-57dea656-2e22-4a8a-b7c4-a2c3631a4c88.png)
![Group 17](https://user-images.githubusercontent.com/68994507/184802999-a96981b5-4d53-46b0-aa21-c5d996832171.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle post requests for signing in
- [x]  Server checks for username and password, retrieves hashed password and checks for match
- [x] If matches, create token with jwt containing user id and username, send to client
- [x] Create authorization middleware with jwt for checking if a user is authenticated (logged in)
- [x] Add authorization middleware to `server/index.js` for all actions available after signing in
- [x] Add JWT error handling to error middleware for invalid access
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

Sign In page:
- [x] Update app component to use context for passing path
- [x] Update components to display sign in page and form
- [x] Update component to send post sign in request to server when submitting form
- [x] Update component to check for received token from server
- [x] Update component to display error message when username or password are invalid
- [x] Update component to give option for user to sign up if they do not have account
- [x] Update component to allow for user to sign in if they already have an account

Signing In:
- [x] Create redirect component for redirecting to sign in page if not authenticated or user profile if authenticated
- [x] Update component to store token in local storage when signing in
- [x] Redirect to user profile after signing in
- [x] Make sure user stays signed-in when refreshing the page
- [x] Update  app to get user information and pass to children as context
- [x] Update creating workout (page is exercises.jsx) to use user id from context
- [x] Update completing workout to use user id from context

Signing Out:
- [x] Update component to remove token from local storage when clicking sign out
- [x] Reroute to sign in page when signing out
- [x] Test sign in with wrong username and password
- [x] Test sign in with correct account, should redirect to user profile
- [x] Test reloading page, remains logged in
- [x] Make sure user is authenticated when signed in (test adding, editing and deleting workouts)

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
