### ISSUE TITLE
User can view the exercise list sorted alphabetically

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the exercise list sorted alphabetically

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When view the exercise list, a user is able to view the alphabet in order to skip to different letters and view exercises that begin with that letter

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![View Exercise List (mobile) #1](https://user-images.githubusercontent.com/68994507/186259502-909ae94f-f24b-4fb4-bd95-2adbe9830ce3.png)

Desktop
![View exercise list (desktop) #1](https://user-images.githubusercontent.com/68994507/186259484-99a581c2-f935-41ed-b98f-630c3c19f87c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to sort exercises from fetch request (inside `sql` query) 
- [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Update component to display a button for each letter in a container at top of page
- [x] Update component to display a section header for each letter
- [x] Update component to render exercises according to their letter
- [x] Add function to alphabet buttons to handle scroll on click
- [x] Add id to each letter header section to get element
- [x] Make sure desktop view displays two exercises per row but keeping letter title full width
- [x] Add a button to scroll to top on right side of screen
- [x] Add function which handles scrolling to top
- [x] Make sure button will stick to page even when scrolling

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
