### ISSUE TITLE
User can search for exercise by name

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for exercise by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When adding exercises to a workout, a user can use a search box input to search for exercise names. The matching results are shown at the top of the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
Mobile
![Group 14](https://user-images.githubusercontent.com/68994507/186283440-15a31033-daec-46ca-9448-0f0ceaba7edf.png)

Desktop
![Group 18](https://user-images.githubusercontent.com/68994507/186283427-51f896e3-ef65-4712-86a9-c7c803eb6bf4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update exercise component to include an input search box at the top of the page, after the title
- [x] Update component to save the changing value by updating state
- [x] Create function that filters the exercise list with the updated state to display matching exercise cards
- [x] Create functionality which goes back to displaying all exercises if nothing is typed in the search box
- [x] Style search box and make responsive
- [x] Make sure selected exercises within a search remains selected when resetting or deleting search values

### 🧑‍⚕️ Clean Up Tasks

- [x] Fix sign up display message and re routing when encountering an error.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
