### ISSUE TITLE
User can view workout frequency

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view workout frequency in a chart

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user is able to go to frequency page and view a chart on the number of workouts by week.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![View progress (mobile) #1](https://user-images.githubusercontent.com/68994507/187047932-ead7b3e6-858c-4ef8-a06e-846e285769ef.png)

Desktop
![View Progress (desktop) #1](https://user-images.githubusercontent.com/68994507/187047930-44fd2344-97f2-41d8-90c6-e04253a7de14.png)

## ✅ Task Lists

- [x] Install chart.js, react-chart-js-2 and required dependencies

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include workout completed date and time

### ☁️ Server Tasks

- [x] Update `server/index.js` to add "completedAt" time to previous requests where necessary
- [x] Update `server/index.js` to add "completedAt" time to workouts column in new patch request
- [x] Update `server/index.js` to get all completed workouts from the user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update save workout component to save a workout's completed date to server and time when submitting workout
- [x] Update user profile workout cards to display completed date and time for each workout
- [x] Create a page to render chart
- [x] Calculate and display last 8 weeks from current date on x-axis
- [x] Update component to fetch a user's workouts
- [x] Update component to count total number of workouts per week over the last 8 weeks and render on bar chart
- [x] Add workout frequency link to bottom navbar and top navbar
- [x] Add hash routing to workout frequency
- [x] Make sure workouts in the user profile render starting from latest workout

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
