### ISSUE TITLE
User can replace an exercise during workout

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 14](https://user-images.githubusercontent.com/68994507/190295888-794f19cd-b7c9-41f4-ab12-7e867ef3b7b1.png)
![Group 14 (1)](https://user-images.githubusercontent.com/68994507/190295895-ac2076f4-c096-4cac-914b-148c803f35c7.png)

Desktop
![Group 19](https://user-images.githubusercontent.com/68994507/190296777-6cf3afb9-e930-4e84-9b31-5d9cc5ddbb6b.png)
![Group 19 (1)](https://user-images.githubusercontent.com/68994507/190296785-e2ba6b17-341c-4f45-9984-72af981596b7.png)
![Delete Exercise (desktop) #1](https://user-images.githubusercontent.com/68994507/190296792-c42f92bf-9af0-406d-b254-37148429d712.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to update a workout's id through workouts and exercise ids

### ⚡ Client Tasks

- [x] Create exercise in workout component to display replace option when clicking settings
- [x] Update component to open modal for selecting exercises to chose from 
- [x] Display exercise being replaced at top of modal
- [x] Create fetch request to server for all exercises to be displayed on modal
- [x] Display all exercise cards
- [x] Display exercise list with letter jump to buttons and search bar
- [x] Make sure jump to letter works
- [x] Make sure search bar works
- [x] Add replace and cancel button
- [x] Make sure cancel button exits modal
- [x] Make sure only one exercise can be selected (if one exercise already selected, deselect it and select new one)
- [x] Add replace submit to patch API to replace exercise in database after clicking replace button
- [x] After clicking replace, the state of the workout (exercises) should also be updated with new exercise name and id
- [x] Update component to receive which exercise is being replace as props when clicking 'replace' option
- [x] After replacing the exercise, the new exercise name should appear in place of previous exercise
- [x] Make sure exercise info is updated in state

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure pop up 'replace' button is responsive
- [x] Make sure modal is responsive
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
