### ISSUE TITLE
User can name and rename workouts

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can name and rename workouts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When creating a new workout, users are able to type the name of a workout. Additionally, when a user is on their profile, they can edit workout names by clicking an icon on the workout card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Group 14](https://user-images.githubusercontent.com/68994507/199086755-8b1b9aa5-694a-46bd-8e69-1c2b8f9f59a2.png)

Desktop:
![Group 18](https://user-images.githubusercontent.com/68994507/199086774-d7f582e0-8c4c-44f8-9606-cca0e3d48712.png)
![Group 19](https://user-images.githubusercontent.com/68994507/199086776-c3f18833-3555-4125-a492-282a2301592f.png)
![View Workout History (desktop) #1](https://user-images.githubusercontent.com/68994507/199086778-baf90cc7-1615-4efc-ba27-40d6ce075ae9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a name column in each workout

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a workout name when creating a new workout
- [x] Update `server/index.js` to patch a workout name
- [x] Update `server/index.js` to delete workouts that are not completed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add label and input to `new-workout.jsx` form for workout name
- [x] Make sure workout name state is updated when edited and includes placeholder name if no edits are made
- [x] Make sure to include placeholder workout name
- [x] Update component to send patch request with the workout name on submission
- [x] Update `workout.jsx` to display the created workout name from fetching the workout
- [x] Update component to include icon for renaming the workout
- [x] Update `user-profile.jsx` workout cards to display workout name from fetching workouts

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
