### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/strive-workout-tracker#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account by signing up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When opening the website, the sign up page is the first page that users are redirected to.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![Group 13](https://user-images.githubusercontent.com/68994507/184721962-faaac58a-ca78-46cb-ab05-cbc673d8715b.png)

Desktop
![Group 15](https://user-images.githubusercontent.com/68994507/184721997-d3c2c0d6-93cb-4635-ae57-a45397f8dbcb.png)
![Sign Up (desktop) #1](https://user-images.githubusercontent.com/68994507/184722009-ac858d83-0653-462d-aa96-acab5979322b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add argon2 to `package.json` and import package
- [x] Update `server/index.js` to receive post request for creating new user accounts (username, password)
- [x] When receiving the request, hash the password with argon2 before sending to database
- [x] Update `server/index.js` to receive get request for all usernames
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render the sign up page and component for form with two inputs, username and password and a button to submit form
- [x] Create onchange input event listeners to username and password
- [x] Create fetch request to get all username information which checks if the new username matches any pre existing usernames
- [x] Make error message display when username already exists
- [x] Create on submit event handler which sends the patch request to the server to save the users' information
- [x] Make success message display when user successfully signs up
- [x] Update component to not show user-profile and workout links on navbars

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
